@extends('layouts.app')
@section('title', 'سفارش '.$order->reference)
@section('hero')<span class="badge">بلیت‌های من</span><h1>{{ $order->status === 'paid' ? 'خرید شما با موفقیت انجام شد' : 'جزئیات سفارش' }}</h1><p>کد پیگیری سفارش: {{ $order->reference }}</p>@endsection
@section('content')
@php($firstItem=$order->items->first())
<div class="grid"><section class="card"><h2>اطلاعات سفارش</h2><div class="summary-line"><span>خریدار</span><strong>{{ $order->customer_name }}</strong></div><div class="summary-line"><span>وضعیت</span><span class="badge {{ $order->status === 'paid' ? 'published' : 'scheduled' }}">{{ ['paid'=>'پرداخت‌شده','pending'=>'در انتظار پرداخت','expired'=>'منقضی‌شده','cancelled'=>'لغوشده'][$order->status] ?? $order->status }}</span></div><div class="summary-line"><span>مبلغ</span><strong>{{ number_format($order->total_amount) }} تومان</strong></div><div class="summary-line"><span>تاریخ پرداخت</span><strong>{{ $order->paid_at?->format('Y/m/d H:i') ?? '—' }}</strong></div></section>@if($firstItem)<section class="card"><h2>{{ $firstItem->performanceSeat->performance->event->title }}</h2><p>{{ $firstItem->performanceSeat->performance->starts_at->format('Y/m/d H:i') }}</p><p class="muted">{{ $firstItem->performanceSeat->performance->hall->venue->name }} / {{ $firstItem->performanceSeat->performance->hall->name }}</p></section>@endif</div>
<div class="grid" style="margin-top:20px">@forelse($order->items as $item)<article class="ticket-card"><span class="badge">صندلی {{ $item->performanceSeat->seat->code }}</span><h2>{{ $item->performanceSeat->performance->event->title }}</h2><p>{{ $item->performanceSeat->performance->starts_at->format('Y/m/d - H:i') }}</p><div class="summary-line"><span>ردیف</span><strong>{{ $item->performanceSeat->seat->row_label }}</strong></div><div class="summary-line"><span>شماره صندلی</span><strong>{{ $item->performanceSeat->seat->number }}</strong></div>@if($item->ticket)<p>کد بلیت</p><span class="ticket-code">{{ $item->ticket->code }}</span>@else<p class="alert error">بلیت پس از تکمیل پرداخت صادر می‌شود.</p>@endif</article>@empty<div class="card">این سفارش بلیتی ندارد.</div>@endforelse</div>
<div class="button-row" style="margin-top:24px"><button class="btn secondary" onclick="window.print()">چاپ بلیت‌ها</button><a class="btn secondary" href="{{ route('tickets.index') }}">بازیابی سفارش دیگر</a></div>
@endsection
