@extends('layouts.app')
@section('title', 'جزئیات سفارش')
@section('content')
@php($firstItem=$order->items->first())
<div class="section-title"><div><h1>جزئیات سفارش</h1><p class="page-subtitle">{{ $order->reference }}</p></div><a class="btn secondary" href="{{ route('admin.orders.index') }}">بازگشت به سفارش‌ها</a></div>
<div class="stats"><div class="card stat"><span class="muted">وضعیت</span><strong style="font-size:20px">{{ ['paid'=>'پرداخت‌شده','pending'=>'در انتظار پرداخت','expired'=>'منقضی‌شده','cancelled'=>'لغوشده'][$order->status] ?? $order->status }}</strong></div><div class="card stat"><span class="muted">مبلغ کل</span><strong style="font-size:20px">{{ number_format($order->total_amount) }}</strong><small>تومان</small></div><div class="card stat"><span class="muted">تعداد بلیت</span><strong>{{ $order->items->count() }}</strong></div><div class="card stat"><span class="muted">زمان ثبت</span><strong style="font-size:17px">{{ $order->created_at->format('Y/m/d H:i') }}</strong></div></div>
<div class="grid" style="margin-top:18px"><section class="card"><h2>اطلاعات خریدار</h2><div class="summary-line"><span>نام</span><strong>{{ $order->customer_name }}</strong></div><div class="summary-line"><span>موبایل</span><strong>{{ $order->customer_phone }}</strong></div><div class="summary-line"><span>ایمیل</span><strong>{{ $order->customer_email }}</strong></div></section><section class="card"><h2>پرداخت</h2><div class="summary-line"><span>شناسه پرداخت</span><strong>{{ $order->payment_reference ?? '—' }}</strong></div><div class="summary-line"><span>زمان پرداخت</span><strong>{{ $order->paid_at?->format('Y/m/d H:i') ?? '—' }}</strong></div><div class="summary-line"><span>مهلت رزرو</span><strong>{{ $order->reserved_until->format('Y/m/d H:i') }}</strong></div></section></div>
@if($firstItem)<section class="card" style="margin-top:18px"><h2>{{ $firstItem->performanceSeat->performance->event->title }}</h2><div class="event-meta"><span>◷ {{ $firstItem->performanceSeat->performance->starts_at->format('Y/m/d H:i') }}</span><span>⌖ {{ $firstItem->performanceSeat->performance->hall->venue->name }} / {{ $firstItem->performanceSeat->performance->hall->name }}</span></div></section>@endif
<section class="card" style="margin-top:18px;padding:0"><div class="section-title" style="padding:20px 20px 0"><h2>بلیت‌ها و صندلی‌ها</h2></div><div class="table-wrap"><table class="table"><tr><th>صندلی</th><th>ردیف</th><th>شماره</th><th>مبلغ</th><th>کد بلیت</th></tr>@foreach($order->items as $item)<tr><td>{{ $item->performanceSeat->seat->code }}</td><td>{{ $item->performanceSeat->seat->row_label }}</td><td>{{ $item->performanceSeat->seat->number }}</td><td>{{ number_format($item->unit_price) }}</td><td><code>{{ $item->ticket?->code ?? 'صادر نشده' }}</code></td></tr>@endforeach</table></div></section>
@endsection
