@extends('layouts.app')
@section('title', $event->title)
@section('content')
@php($publicationStatus = $event->publicationStatus())
<div class="section-title">
    <div><div class="button-row"><span class="badge {{ $publicationStatus }}">{{ ['published'=>'فعال','scheduled'=>'زمان‌بندی‌شده','draft'=>'پیش‌نویس'][$publicationStatus] }}</span><span class="badge">{{ $event->type === 'concert' ? 'کنسرت' : 'تئاتر' }}</span></div><h1 style="margin-bottom:0">{{ $event->title }}</h1><p class="page-subtitle">/{{ $event->slug }}</p></div>
    <div class="button-row"><a class="btn secondary" href="{{ route('admin.events.edit', $event) }}">✎ ویرایش</a><form method="post" action="{{ route('admin.events.publication.toggle', $event) }}">@csrf @method('PATCH')<button class="btn {{ $event->isPublished() ? 'danger' : 'success' }}">{{ $event->isPublished() ? 'غیرفعال‌کردن' : 'فعال‌سازی فوری' }}</button></form></div>
</div>
<div class="grid">
    <section class="card"><h3>وضعیت انتشار</h3>@if($event->isPublished())<p><span class="badge published">در سایت فعال است</span></p><p class="muted">فعال‌شده در {{ $event->published_at->format('Y/m/d H:i') }}</p>@elseif($event->isScheduled())<p><span class="badge scheduled">انتشار خودکار</span></p><p>این رویداد در <strong>{{ $event->published_at->format('Y/m/d H:i') }}</strong> خودکار نمایش داده می‌شود.</p>@else<p><span class="badge draft">پیش‌نویس</span></p><p class="muted">برای کاربران قابل مشاهده نیست.</p>@endif<a href="{{ route('admin.events.edit', $event) }}">تغییر زمان‌بندی ←</a></section>
    <section class="card"><h3>اطلاعات رویداد</h3><p class="muted">مدت اجرا: {{ $event->duration_minutes ? $event->duration_minutes.' دقیقه' : 'ثبت نشده' }}</p><p class="muted">محدودیت سنی: {{ $event->age_limit ?? 'ندارد' }}</p><p>{{ Str::limit($event->description, 160) }}</p></section>
</div>
<section class="card" style="margin-top:18px"><div class="section-title"><div><h2>افزودن سانس</h2><p class="page-subtitle">با ثبت سانس، موجودی صندلی‌های سالن ایجاد می‌شود.</p></div></div>@if($halls->isEmpty())<div class="alert error">ابتدا یک سالن دارای صندلی بسازید.</div>@else<form method="post" action="{{ route('admin.performances.store', $event) }}" class="form-grid">@csrf<label class="field"><span>سالن</span><select name="hall_id">@foreach($halls as $hall)<option value="{{ $hall->id }}">{{ $hall->venue->name }} / {{ $hall->name }} ({{ $hall->capacity }})</option>@endforeach</select></label><label class="field"><span>زمان اجرا</span><input name="starts_at" type="datetime-local" required></label><label class="field"><span>شروع فروش</span><input name="sales_start_at" type="datetime-local"></label><label class="field"><span>پایان فروش</span><input name="sales_end_at" type="datetime-local"></label><label class="field"><span>قیمت پایه (تومان)</span><input name="default_price" type="number" min="0" required></label><div style="align-self:end"><button class="btn">ثبت سانس</button></div></form>@endif</section>
<section class="card" style="margin-top:18px;padding:0"><div class="section-title" style="padding:20px 20px 0"><h2>سانس‌ها</h2><span class="muted">{{ $event->performances->count() }} سانس</span></div><div class="table-wrap"><table class="table"><tr><th>زمان اجرا</th><th>مجموعه / سالن</th><th>شروع فروش</th><th>پایان فروش</th><th>وضعیت</th></tr>@forelse($event->performances as $performance)<tr><td><strong>{{ $performance->starts_at->format('Y/m/d H:i') }}</strong></td><td>{{ $performance->hall->venue->name }} / {{ $performance->hall->name }}</td><td>{{ $performance->sales_start_at?->format('Y/m/d H:i') ?? 'فوری' }}</td><td>{{ $performance->sales_end_at?->format('Y/m/d H:i') ?? 'تا اجرا' }}</td><td><span class="badge">{{ $performance->status }}</span></td></tr>@empty<tr><td colspan="5">هنوز سانسی ثبت نشده است.</td></tr>@endforelse</table></div></section>
@endsection
